biblioteca/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', include(('account.urls', 'account'), namespace='account')),
    path('', include(('loan.urls', 'loan'), namespace='loan')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
"""Catalog URLs."""

# Django
from django.urls import path
from django.contrib.auth.decorators import login_required
# Views
from catalog import views

urlpatterns = [

    path(
        route='',
        view = views.home,
        name='home'
    ),

    #################################################
    ############ MATERIAL BIBLIOGRAFICO #############
    #################################################

    ########## CRUD de Autor ##########
    path(
        route='listar_autor/',
        view=login_required(views.ListadoAutorView.as_view()),
        name='listar_autor'
    ),
    path(
        route='crear_autor/',
        view=login_required(views.CrearAutorView.as_view()),
        name='crear_autor'
    ),
    path(
        route='editar_autor/<int:pk>/',
        view=login_required(views.ActualizarAutorView.as_view()),
        name='editar_autor'
    ),
    path(
        route='eliminar_autor/<int:pk>/',
        view=login_required(views.EliminarAutorView.as_view()),
        name='eliminar_autor'
    ),

    ########## CRUD de Editorial ##########
    path(
        route='listar_editorial/',
        view=login_required(views.ListadoEditorialView.as_view()),
        name='listar_editorial'
    ),
    path(
        route='crear_editorial/',
        view=login_required(views.CrearEditorialView.as_view()),
        name='crear_editorial'
    ),
    path(
        route='editar_editorial/<int:pk>/',
        view=login_required(views.ActualizarEditorialView.as_view()),
        name='editar_editorial'
    ),
    path(
        route='eliminar_editorial/<int:pk>/',
        view=login_required(views.EliminarEditorialView.as_view()),
        name='eliminar_editorial'
    ),

    ########## CRUD de Ubicación ##########
    path(
        route='listar_ubicacion/',
        view=login_required(views.ListadoUbicacionView.as_view()),
        name='listar_ubicacion'
    ),
    path(
        route='crear_ubicacion/',
        view=login_required(views.CrearUbicacionView.as_view()),
        name='crear_ubicacion'
    ),
    path(
        route='editar_ubicacion/<int:pk>/',
        view=login_required(views.ActualizarUbicacionView.as_view()),
        name='editar_ubicacion'
    ),
    path(
        route='eliminar_ubicacion/<int:pk>/',
        view=login_required(views.EliminarUbicacionView.as_view()),
        name='eliminar_ubicacion'
    ),

    ########## CRUD de Libro ##########
    path(
        route='listar_libros/',
        view=login_required(views.ListadoLibrosView.as_view()),
        name='listar_libros'
    ),
    path(
        route='crear_libro/',
        view=login_required(views.CrearLibroView.as_view()),
        name='crear_libro'
    ),
    path(
        route='editar_libro/<int:pk>/',
        view=login_required(views.ActualizarLibroView.as_view()),
        name='editar_libro'
    ),
    path(
        route='eliminar_libro/<int:pk>/',
        view=login_required(views.EliminarLibroView.as_view()),
        name='eliminar_libro'
    ),

    ########## Detalles de Libro ##########
    path(
        route='detalle_libro/<slug:slug>/<int:pk>/',
        view=login_required(views.LibroDetailView.as_view()),
        name='libro_detail'
    ),

    ########## CRUD de Ejemplares ##########
    path(
        route='crear_ejemplar/<int:pk>/',
        view=login_required(views.CrearEjemplarView.as_view()),
        name='crear_ejemplar'
    ),

    #################################################
    ########### MATERIAL NO BIBLIOGRAFICO ###########
    #################################################

    ########## CRUD de Material ##########
    path(
        route='listar_material/',
        view=login_required(views.ListadoMaterialView.as_view()),
        name='listar_material'
    ),
    path(
        route='crear_material/',
        view=login_required(views.CrearMaterialView.as_view()),
        name='crear_material'
    ),
    path(
        route='editar_material/<int:pk>/',
        view=login_required(views.ActualizarMaterialView.as_view()),
        name='editar_material'
    ),
    path(
        route='eliminar_material/<int:pk>/',
        view=login_required(views.EliminarMaterialView.as_view()),
        name='eliminar_material'
    ),

    ########## Detalles de Material ##########
    path(
        route='detalle_material/<slug:slug>/<int:pk>/',
        view=login_required(views.MaterialDetailView.as_view()),
        name='material_detail'
    ),

    ########## CRUD de Ejemplares ##########
    path(
        route='crear_ejemplar_material/<int:pk>/',
        view=login_required(views.CrearEjemplarMaterialView.as_view()),
        name='crear_ejemplar_material'
    ),
]

loan/urls.py
"""Loan URLs."""

# Django
from django.urls import path
from django.contrib.auth.decorators import login_required
# Views
from loan import views

urlpatterns = [
    
    ########### MATERIAL BIBLIOGRAFICO ###########
    path(
        route='listar_prestamos/',
        view=login_required(views.ListadoPrestamoView.as_view()),
        name='listar_prestamos'
    ),

    ########### Prestamos/Devolución desde Inicio ###########
    path(
        route='crear_prestamo/',
        view=login_required(views.CrearPrestamoView.as_view()),
        name='crear_prestamo'
    ),
    path(
        route='devolucion/',
        view=login_required(views.DevolucionView.as_view()),
        name='devolucion'
    ),

    ########### Prestamos/Devolución desde Usuario ###########
    path(
        route='nuevo_prestamo/<int:pk>/<slug:slug>/',
        view=login_required(views.NuevoPrestamoView.as_view()),
        name='nuevo_prestamo'
    ),
    path(
        route='devolver_prestamo/<int:pk_ejemplar>/<int:pk_lector>/',
        view=login_required(views.DevolverPrestamoView.as_view()),
        name='devolver_prestamo'
    ),

    #################################################
    ########### MATERIAL NO BIBLIOGRAFICO ###########
    path(
        route='listar_prestamos_material/',
        view=login_required(views.ListadoPrestamoMaterialView.as_view()),
        name='listar_prestamos_material'
    ),

    ########### Prestamos/Devolución de Material ###########
    path(
        route='crear_prestamo_material/',
        view=login_required(views.CrearPrestamoMaterialView.as_view()),
        name='crear_prestamo_material'
    ),
    path(
        route='devolucion_material/',
        view=login_required(views.DevolucionMaterialView.as_view()),
        name='devolucion_material'
    ),

]

catalog/models.py
from django.db import models
from django.template.defaultfilters import slugify


class ModeloBase(models.Model):
    status = models.BooleanField('Status', default = True)
    fecha_creacion = models.DateField('Fecha de Creación', auto_now=False, auto_now_add=True)
    fecha_modificacion = models.DateField('Fecha de Modificación', auto_now=True, auto_now_add=False)
    
    class Meta:
        abstract = True


##############################################
########### MATERIAL BIBLIOGRAFICO ###########
##############################################

class Autor(ModeloBase):

    nombre = models.CharField('Nombres', max_length=100)
    apellido = models.CharField('Apellidos', max_length=100)

    class Meta:
        verbose_name='Autor'
        verbose_name_plural='Autores'

    def __str__(self):
        return '%s, %s' % (self.apellido, self.nombre)


class Editorial(ModeloBase):

    editorial = models.CharField('Editorial', max_length=100, unique=True)

    class Meta:
        verbose_name='Editorial'
        verbose_name_plural='Editoriales'

    def __str__(self):
        return self.editorial


class Ubicacion(ModeloBase):

    ubicacion = models.CharField('Ubicación', max_length=100, unique=True)

    class Meta:
        verbose_name='Ubicacion'
        verbose_name_plural='Ubicacion'

    def __str__(self):
        return self.ubicacion


class Libro(ModeloBase):

    titulo = models.CharField('Título del Libro', max_length=150)
    portada = models.ImageField(
        'Portada del Libro',
        upload_to='catalog/portadas',
        blank=True,
        null=True
    )

    autor = models.ManyToManyField(Autor, related_name='libro_autor')
    editorial = models.ForeignKey(Editorial, on_delete=models.CASCADE, related_name='libro_editorial')
    
    CATEGORIA = (
        ('referencia', 'Referencia'),
        ('complementarios', 'Complementarios'),
        ('recreativos', 'Recreativos'),
        ('textos', 'Textos'),
        ('pedagogicos', 'Pedagógicos'),
        ('publicaciones periodicas', 'Publicaciones Periódicas'),
        ('seccion docentes', 'Sección Docentes'),
    )

    categoria = models.CharField(max_length=20, choices=CATEGORIA, blank=True, help_text='Clasificación Dewey')
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE, related_name='libro_ubicacion')

    class Meta:
        verbose_name='Libro'
        verbose_name_plural='Libros'

    def __str__(self):
        return self.titulo

    @property
    def slug(self):
        return slugify(self.titulo)


class EjemplarLibro(ModeloBase):

    libro = models.ForeignKey(Libro, on_delete=models.CASCADE, related_name='ejemplar_libro')

    cota = models.CharField('Cota', max_length=100, unique=True)
    
    CONDICION = (
        ('excelente', 'Excelente'),
        ('regular', 'Regular'),
        ('dañado', 'Dañado'),
    )
    condicion = models.CharField(max_length=20, choices=CONDICION, blank=True, help_text='Condicion del ejemplar')

    ADQUIRIDO = (
        ('donacion', 'Donacion'),
        ('comprado', 'Comprado'),
    )
    adquirido = models.CharField(max_length=20, choices=ADQUIRIDO, blank=True, help_text='Como fue adquirido el ejemplar')

    ESTADO = (
        ('disponible', 'Disponible'),
        ('prestado', 'Prestado'),
    )
    estado = models.CharField(max_length=20, choices=ESTADO, blank=True, default='disponible', help_text='Disponibilidad del ejemplar')

    class Meta:
        verbose_name='Ejemplar'
        verbose_name_plural='Ejemplares'

    def __str__(self):
        return '%s, ejemplar: %s' % (self.libro.titulo, self.cota)


#################################################
########### MATERIAL NO BIBLIOGRAFICO ###########
#################################################

class Material(ModeloBase):

    material = models.CharField('Material', max_length=100)
    descripcion = models.CharField('Descripción', max_length=200, blank=True, null=True)

    imagen = models.ImageField(
        'Imagen de Referencia',
        upload_to='catalog/materiales',
        blank=True,
        null=True
    )
    
    CATEGORIA = (
        ('mapas', 'Mapas'),
        ('meni', 'Material Educativo no Impreso'),
        ('juegos', 'Juegos Didácticos'),
        ('otros', 'Otros'),
    )
    categoria = models.CharField(max_length=20, choices=CATEGORIA, blank=True)

    class Meta:
        verbose_name='Material no Bibliografico'
        verbose_name_plural='Material no Bibliografico'

    def __str__(self):
        return self.material

    @property
    def slug(self):
        return slugify(self.material)

class EjemplarMaterial(ModeloBase):

    material = models.ForeignKey(Material, on_delete=models.CASCADE, related_name='ejemplar_material')
    
    CONDICION = (
        ('excelente', 'Excelente'),
        ('regular', 'Regular'),
        ('dañado', 'Dañado'),
    )
    condicion = models.CharField(max_length=20, choices=CONDICION, blank=True, help_text='Condicion del ejemplar')

    ADQUIRIDO = (
        ('donacion', 'Donacion'),
        ('comprado', 'Comprado'),
    )
    adquirido = models.CharField(max_length=20, choices=ADQUIRIDO, blank=True, help_text='Como fue adquirido el ejemplar')

    ESTADO = (
        ('disponible', 'Disponible'),
        ('prestado', 'Prestado'),
    )
    estado = models.CharField(max_length=20, choices=ESTADO, blank=True, default='disponible', help_text='Disponibilidad del ejemplar')

    class Meta:
        verbose_name='Ejemplar no Bibliografico'
        verbose_name_plural='Ejemplares no Bibliograficos'

    def __str__(self):
        return '%s, ejemplar: %s' % (self.material.material, self.pk)

catalog/forms.py
"""Catalog forms."""

# Django
from django import forms

# Models
from catalog.models import Autor, Editorial, Ubicacion, Libro, EjemplarLibro, Material, EjemplarMaterial


##############################################
########### MATERIAL BIBLIOGRAFICO ###########
##############################################

class AutorForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(AutorForm, self).__init__(*args, **kwargs)
        file = []
        for field in self.fields:
            if not (field in file):
                self.fields[field].widget.attrs['class'] = 'form-control'

    class Meta:

        model = Autor
        fields = (
            'nombre',
            'apellido',
        )


class EditorialForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(EditorialForm, self).__init__(*args, **kwargs)
        file = []
        for field in self.fields:
            if not (field in file):
                self.fields[field].widget.attrs['class'] = 'form-control'

    class Meta:

        model = Editorial
        fields = (
            'editorial',
        )


class UbicacionForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(UbicacionForm, self).__init__(*args, **kwargs)
        file = []
        for field in self.fields:
            if not (field in file):
                self.fields[field].widget.attrs['class'] = 'form-control'

    class Meta:

        model = Ubicacion
        fields = (
            'ubicacion',
        )


class LibroForm(forms.ModelForm):

    class Meta:
        model = Libro
        
        fields = (
            'titulo',
            'portada',
            'autor',
            'editorial',
            'categoria',
            'ubicacion',
        )

        widgets = {
            'titulo': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }),

            'portada': forms.FileInput(
                attrs={
                    'class': 'custom-file-input',
                    'lang': 'es',
                }),

            'autor': forms.SelectMultiple(
                attrs={
                    'class': 'standardSelect',
                    'data-placeholder': 'Selecciona autor o autores...',
                }),

            'editorial': forms.Select(
                attrs={
                    'class': 'standardSelect',
                    'data-placeholder': 'Selecciona editorial...',
                }),

            'categoria': forms.Select(
                attrs={
                    'class': 'standardSelect',
                    'data-placeholder': 'Selecciona categoria...',
                }),

            'ubicacion': forms.Select(
                attrs={
                    'class': 'standardSelect',
                    'data-placeholder': 'Seleccione ubicación...',
                }),
        }


class EjemplarLibroForm(forms.ModelForm):

    class Meta:

        model = EjemplarLibro
        fields = (
            'libro',
            'cota',
            'condicion',
            'adquirido',
            'estado',
        )


#################################################
########### MATERIAL NO BIBLIOGRAFICO ###########
#################################################

class MaterialForm(forms.ModelForm):

    class Meta:
        model = Material
        
        fields = (
            'material',
            'descripcion',
            'categoria',
        )

        widgets = {
            'material': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }),

            'descripcion': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }),

            'categoria': forms.Select(
                attrs={
                    'class': 'standardSelect',
                    'data-placeholder': 'Selecciona categoria...',
                }),
        }


class EjemplarMaterialForm(forms.ModelForm):

    class Meta:

        model = EjemplarMaterial
        fields = (
            'material',
            'condicion',
            'adquirido',
            'estado',
        )

templates/catalog/material/crear_material.html
{% extends "layout.html" %}
{% load static %}

{% block titulo %}
Nuevo Material
{% endblock %}

{% block css %}
  <style type="text/css">

    .custom-file-label:after{
      content: "Elegir";
    }

  </style>
{% endblock %}

{% block content %}

<div class="col-xs-12 offset-sm-3 col-sm-6">
  <div class="card">
    <div class="card-header">
      <strong>Formulario de {{ title }}</strong>
    </div>
    <div class="card-body card-block">

      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          <label for="id_titulo" class="form-control-label"> {{ form.material.label }} </label>
          {{ form.material }}
        </div>
        
        <div class="form-group">
          <label class=" form-control-label"> {{ form.descripcion.label }} </label>
          {{ form.descripcion }}
        </div>

        <div class="form-group">
          <label class=" form-control-label"> {{ form.categoria.label }} </label>
          {{ form.categoria }}
        </div>

        <button type="submit" class="btn btn-primary">Guardar</button>
        <button type="reset" class="btn btn-danger">Cancelar</button>

      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}
<script src="{% static 'assets/js/dist_lib/chosen/chosen.jquery.min.js' %}"></script>
<script src="{% static 'assets/js/bs-custom-file-input.min.js' %}"></script>

<script>

jQuery(document).ready(function() {
  jQuery(".standardSelect").chosen({
    disable_search_threshold: 10,
    no_results_text: "Oops, nothing found!",
    width: "100%"
  });
});

jQuery(document).ready(function(){
  bsCustomFileInput.init()
});

</script>

{% endblock %}

templates/catalog/material/listar_material.html
{% extends "layout.html" %}
{% load static %}

{% block titulo %}
Listado de Material
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/datatable/dataTables.bootstrap.min.css' %}">
  <style type="text/css">
  </style>
{% endblock %}

{% block content %}


{% if materiales %}

<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Listado de Materiales</strong>
    </div>
    <div class="card-body">
      <table id="bootstrap-data-table" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>inventario</th>
            <th>material</th>
            <th>descripcion</th>
            <th>categoria</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for material in materiales %}
          <tr>
            <td>{{ material.ejemplar_material.all|length }}</td>
            <td>{{ material.material }}</td>
            <td> {{ material.descripcion }} </td>
            <td> {{ material.categoria }} </td>
            <td>
              <a href="{% url 'catalog:material_detail' slug=material.slug pk=material.pk %}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="top" title="Ver detalles"><i class="fa fa-search"></i></a>
              <a href="{% url 'catalog:editar_material' material.id %}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="top" title="Editar"><i class="fa fa-pencil-square-o"></i></a>
              <a href="{% url 'catalog:eliminar_material' material.id %}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="fa fa-trash-o"></i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% else %}
<h3>No existen materiales registrados</h3>
{% endif %}

{% endblock %}

{% block js %}

<script src="{% static 'assets/js/dist_lib/data-table/datatables.min.js' %}"></script>

<script src="{% static 'assets/js/dist_lib/data-table/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/dist_lib/data-table/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'assets/js/dist_lib/data-table/buttons.bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/dist_lib/data-table/jszip.min.js' %}"></script>
<script src="{% static 'assets/js/dist_lib/data-table/vfs_fonts.js' %}"></script>
<script src="{% static 'assets/js/dist_lib/data-table/buttons.html5.min.js' %}"></script>
<script src="{% static 'assets/js/dist_lib/data-table/buttons.print.min.js' %}"></script>
<script src="{% static 'assets/js/dist_lib/data-table/buttons.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/init/datatables-init.js' %}"></script>

<script>
  function () {
    $('[data-toggle="tooltip"]').tooltip()
  };
</script>
{% endblock %}

templates/catalog/material/material_confirm_delete.html
{% extends "layout.html" %}
{% load static %}

{% block titulo %}
Confirmacion eliminar material
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}

<div class="col-xs-12 offset-sm-3 col-sm-6">
  <div class="card">
    <div class="card-header">
      <strong>Eliminar Material</strong>
    </div>
    <div class="card-body card-block">

      <form action="" method="POST">
        {% csrf_token %}
          <p><strong>¿Desea eliminar el registro {{ object }}?</strong></p>
          <button type="submit" class="btn btn-danger">Confirmar</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/catalog/material/material_detail.html
{% extends "layout.html" %}
{% load static %}

{% block titulo %}
Detalle Material
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/datatable/dataTables.bootstrap.min.css' %}">
  <style type="text/css">
    .portada{
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .descripcion div{
      padding-bottom: 10px;
    }
  </style>
{% endblock %}

{% block content %}

<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Detalles de Material</strong>
    </div>
    <div class="card-body row">
      <div class="col-md-4 text-center portada">
        {% if object.imagen %}
          <img src="{{ object.imagen.url }}" alt="" style="width: 75%;">
        {% else %}
          <p>No hay imagen</p>
        {% endif %}        
      </div>
      <div class="col-md-8 descripcion">
        <div> Material: {{ object.material }}</div>
        <div> Categoria: {{ object.categoria }}</div>
      </div>
    </div>
  </div>
</div>


<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Ejemplares:</strong>
    </div>
    <div class="card-body">
      {% if object.ejemplar_material.all %}
      <table id="bootstrap-data-table" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Código</th>
            <th>Material</th>
            <th>Condición</th>
            <th>Adquirido</th>
            <th>Estado</th>
          </tr>
        </thead>
        <tbody>
          {% for material in object.ejemplar_material.all %}
          <tr>
            <td>{{ material.id }}</td>
            <td>{{ material.material }}</td>
            <td>{{ material.condicion }}</td>
            <td>{{ material.adquirido }}</td>
            <td>{{ material.estado }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
        <h6>No existen ejemplares registrados</h6>
      {% endif %}
    </div>
  </div>
  <a href="{% url 'catalog:crear_ejemplar_material' pk=object.pk %}" class="btn btn-primary">Agregar ejemplar</a>
</div>

{% endblock %}