account/urls.py
"""Account URLs."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

# Views
from account import views

urlpatterns = [

    path(
        route='listar_perfil/',
        view=login_required(views.ListadoPerfilView.as_view()),
        name='listar_perfil'
    ),

    path(
        route='crear_estudiante/',
        view=login_required(views.CrearEstudianteView.as_view()),
        name='crear_estudiante'
    ),
    path(
        route='editar_perfil/estudiante/<int:pk>/',
        view=login_required(views.ActualizarEstudianteView.as_view()),
        name='editar_estudiante'
    ),

    path(
        route='crear_personal/',
        view=login_required(views.CrearPersonalView.as_view()),
        name='crear_personal'
    ),
    path(
        route='editar_perfil/personal/<int:pk>/',
        view=login_required(views.ActualizarPersonalView.as_view()),
        name='editar_personal'
    ),

    path(
        route='crear_visitante/',
        view=login_required(views.CrearVisitanteView.as_view()),
        name='crear_visitante'
    ),
    path(
        route='editar_perfil/visitante/<int:pk>/',
        view=login_required(views.ActualizarVisitanteView.as_view()),
        name='editar_visitante'
    ),

    path(
        route='crear_bibliotecario/',
        view=login_required(views.CrearBibliotecarioView.as_view()),
        name='crear_bibliotecario'
    ),
    path(
        route='listar_bibliotecario/',
        view=login_required(views.ListadoBibliotecarioView.as_view()),
        name='listar_bibliotecario'
    ),

    
    path(
        route='eliminar_perfil/<int:pk>/',
        view=login_required(views.EliminarPerfilView.as_view()),
        name='eliminar_perfil'
    ),
    path(
        route='perfil/<slug:slug>/<int:pk>/',
        view=login_required( views.PerfilDetailView.as_view()),
        name='perfil_detail'
    ),


    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=login_required(views.LogoutView.as_view()),
        name='logout'
    ),
]

biblioteca/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', include(('account.urls', 'account'), namespace='account')),
    path('', include(('loan.urls', 'loan'), namespace='loan')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
"""Catalog URLs."""

# Django
from django.urls import path
from django.contrib.auth.decorators import login_required
# Views
from catalog import views

urlpatterns = [

    path(
        route='',
        view = views.home,
        name='home'
    ),

    #################################################
    ############ MATERIAL BIBLIOGRAFICO #############
    #################################################

    ########## CRUD de Autor ##########
    path(
        route='listar_autor/',
        view=login_required(views.ListadoAutorView.as_view()),
        name='listar_autor'
    ),
    path(
        route='crear_autor/',
        view=login_required(views.CrearAutorView.as_view()),
        name='crear_autor'
    ),
    path(
        route='editar_autor/<int:pk>/',
        view=login_required(views.ActualizarAutorView.as_view()),
        name='editar_autor'
    ),
    path(
        route='eliminar_autor/<int:pk>/',
        view=login_required(views.EliminarAutorView.as_view()),
        name='eliminar_autor'
    ),

    ########## CRUD de Editorial ##########
    path(
        route='listar_editorial/',
        view=login_required(views.ListadoEditorialView.as_view()),
        name='listar_editorial'
    ),
    path(
        route='crear_editorial/',
        view=login_required(views.CrearEditorialView.as_view()),
        name='crear_editorial'
    ),
    path(
        route='editar_editorial/<int:pk>/',
        view=login_required(views.ActualizarEditorialView.as_view()),
        name='editar_editorial'
    ),
    path(
        route='eliminar_editorial/<int:pk>/',
        view=login_required(views.EliminarEditorialView.as_view()),
        name='eliminar_editorial'
    ),

    ########## CRUD de Ubicación ##########
    path(
        route='listar_ubicacion/',
        view=login_required(views.ListadoUbicacionView.as_view()),
        name='listar_ubicacion'
    ),
    path(
        route='crear_ubicacion/',
        view=login_required(views.CrearUbicacionView.as_view()),
        name='crear_ubicacion'
    ),
    path(
        route='editar_ubicacion/<int:pk>/',
        view=login_required(views.ActualizarUbicacionView.as_view()),
        name='editar_ubicacion'
    ),
    path(
        route='eliminar_ubicacion/<int:pk>/',
        view=login_required(views.EliminarUbicacionView.as_view()),
        name='eliminar_ubicacion'
    ),

    ########## CRUD de Libro ##########
    path(
        route='listar_libros/',
        view=login_required(views.ListadoLibrosView.as_view()),
        name='listar_libros'
    ),
    path(
        route='crear_libro/',
        view=login_required(views.CrearLibroView.as_view()),
        name='crear_libro'
    ),
    path(
        route='editar_libro/<int:pk>/',
        view=login_required(views.ActualizarLibroView.as_view()),
        name='editar_libro'
    ),
    path(
        route='eliminar_libro/<int:pk>/',
        view=login_required(views.EliminarLibroView.as_view()),
        name='eliminar_libro'
    ),

    ########## Detalles de Libro ##########
    path(
        route='detalle_libro/<slug:slug>/<int:pk>/',
        view=login_required(views.LibroDetailView.as_view()),
        name='libro_detail'
    ),

    ########## CRUD de Ejemplares ##########
    path(
        route='crear_ejemplar/<int:pk>/',
        view=login_required(views.CrearEjemplarView.as_view()),
        name='crear_ejemplar'
    ),

    #################################################
    ########### MATERIAL NO BIBLIOGRAFICO ###########
    #################################################

    ########## CRUD de Material ##########
    path(
        route='listar_material/',
        view=login_required(views.ListadoMaterialView.as_view()),
        name='listar_material'
    ),
    path(
        route='crear_material/',
        view=login_required(views.CrearMaterialView.as_view()),
        name='crear_material'
    ),
    path(
        route='editar_material/<int:pk>/',
        view=login_required(views.ActualizarMaterialView.as_view()),
        name='editar_material'
    ),
    path(
        route='eliminar_material/<int:pk>/',
        view=login_required(views.EliminarMaterialView.as_view()),
        name='eliminar_material'
    ),

    ########## Detalles de Material ##########
    path(
        route='detalle_material/<slug:slug>/<int:pk>/',
        view=login_required(views.MaterialDetailView.as_view()),
        name='material_detail'
    ),

    ########## CRUD de Ejemplares ##########
    path(
        route='crear_ejemplar_material/<int:pk>/',
        view=login_required(views.CrearEjemplarMaterialView.as_view()),
        name='crear_ejemplar_material'
    ),
]

loan/urls.py
"""Loan URLs."""

# Django
from django.urls import path
from django.contrib.auth.decorators import login_required
# Views
from loan import views

urlpatterns = [
    
    ########### MATERIAL BIBLIOGRAFICO ###########
    path(
        route='listar_prestamos/',
        view=login_required(views.ListadoPrestamoView.as_view()),
        name='listar_prestamos'
    ),

    ########### Prestamos/Devolución desde Inicio ###########
    path(
        route='crear_prestamo/',
        view=login_required(views.CrearPrestamoView.as_view()),
        name='crear_prestamo'
    ),
    path(
        route='devolucion/',
        view=login_required(views.DevolucionView.as_view()),
        name='devolucion'
    ),

    ########### Prestamos/Devolución desde Usuario ###########
    path(
        route='nuevo_prestamo/<int:pk>/<slug:slug>/',
        view=login_required(views.NuevoPrestamoView.as_view()),
        name='nuevo_prestamo'
    ),
    path(
        route='devolver_prestamo/<int:pk_ejemplar>/<int:pk_lector>/',
        view=login_required(views.DevolverPrestamoView.as_view()),
        name='devolver_prestamo'
    ),

    #################################################
    ########### MATERIAL NO BIBLIOGRAFICO ###########
    path(
        route='listar_prestamos_material/',
        view=login_required(views.ListadoPrestamoMaterialView.as_view()),
        name='listar_prestamos_material'
    ),

    ########### Prestamos/Devolución de Material ###########
    path(
        route='crear_prestamo_material/',
        view=login_required(views.CrearPrestamoMaterialView.as_view()),
        name='crear_prestamo_material'
    ),
    path(
        route='devolucion_material/',
        view=login_required(views.DevolucionMaterialView.as_view()),
        name='devolucion_material'
    ),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'dist_lib/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dist_lib/fontawesome/css/all.min.css' %}">

    <title>{% block titulo %}{% endblock %}</title>
    
    <style type="">
      .logo {
        margin-left: 44%;
      }
      
      .login-active {
        display: flex;
        align-items: center;
        padding: 0 10px;
      }
      .login-active img{
        border-radius: 50%;
        vertical-align: middle;        
        object-fit: cover;
        width: 45px;
        height: 45px;
        margin-right: 5px;
      }
    </style>
    {% block css %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <a href="{% url 'catalog:home' %}">
        <img src="{% static 'images/mpppe.png' %}" alt="Logo AAM" style="height:45px;" class="d-lg-none" >
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav logo">
          <li>
            <a href="{% url 'catalog:home' %}">
              <img src="{% static 'images/mpppe.png' %}" alt="Logo" style="height:45px;" class="d-none d-lg-block" >              
            </a>
          </li>
        </ul>

        {% if request.user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="fa fa-gear"></span></a>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Mi Perfil</a>
                <a class="dropdown-item" href="#">Salir</a>
              </div>
            </li>

            <li class="nav-item active">
              <a class="nav-link login-active" href="#">
                  {% if request.user.profile_user.picture %}
                    <img src="{{ request.user.profile_user.picture.url }}" width="35" height="35">
                  {% else %}
                    <img src="{% static 'images/perfil.png' %}" width="35" height="35">
                  {% endif %}
                  <span> <small> Hola! </small> <br> {{request.user.first_name|upper|default:"Tu Nombre"}} </span>
              </a>
            </li>          
          </ul>
        
        {% else %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Iniciar Sesion</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">Registrarse</a>
            </li>          
          </ul>
        {% endif %}
      
      </div>
    </nav>

    <ul class="nav navbar-nav">
      <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Autores</a>
        <ul class="sub-menu children dropdown-menu">
          <li><a href="{% url 'catalog:crear_autor' %}">Registrar Autor</a></li>
          <li><a href="{% url 'catalog:listar_autor' %}">Listado de Autores</a></li>
        </ul>
      </li>
      <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Libros</a>
        <ul class="sub-menu children dropdown-menu">
          <li><a href="{% url 'catalog:crear_libro' %}">Registrar Libro</a></li>
          <li><a href="{% url 'catalog:listar_libros' %}">Listado de Libros</a></li>
        </ul>
      </li>
      <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Usuarios</a>
        <ul class="sub-menu children dropdown-menu">
          <li><a href="{% url 'account:listar_perfil' %}">Listado de usuarios</a></li>
          <li><a href="{% url 'account:crear_estudiante' %}">Registrar Estudiante</a></li>
          <li><a href="{% url 'account:crear_personal' %}">Registrar Personal</a></li>
          <li><a href="{% url 'account:crear_visitante' %}">Registrar Visitante</a></li>
          <li><a href="{% url 'account:crear_bibliotecario' %}">Registrar Bibliotecario</a></li>
        </ul>
      </li>
      <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Prestamos</a>
        <ul class="sub-menu children dropdown-menu">
          <li><a href="{% url 'loan:crear_prestamo' %}">Registrar Prestamo</a></li>
          <li><a href="{% url 'loan:listar_prestamos' %}">Estadisticas de Prestamos</a></li>
        </ul>
      </li>
    </ul>
    
    <div class="main container">
      {% block content %}{% endblock %}
    </div>

    <script src="{% static 'dist_lib/bootstrap/js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'dist_lib/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'dist_lib/bootstrap/js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block titulo %}Inicio{% endblock %}

{% block css %}
<style>
  #main{
    margin: 0 auto 20px;
  }
  .carousel{
    height: 400px;
  }
  .carousel-inner{
    height: 100%;
  }
  .carousel-item{
    height: 100%;
  }
  .carousel-inner img{
    object-position: 0 -200px;
  }
</style>
{% endblock %}

{% block content %}

<main id="main">
  <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'images/biblioteca1.jpg' %}" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/biblioteca2.jpg' %}" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/biblioteca3.jpg' %}" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>  
</main>

<div class="card">
  <div class="card-header">
    <strong class="card-title"><h2>Misión</h2></strong>
  </div>
  <div class="card-body">
    <p class="card-text">La Escuela Básica “Campo Elías” permite la participación de todos los entes de la colectividad ejidense. Promueve la preservación de los espacios ecológicos.</p>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <strong class="card-title"><h2>Visión</h2></strong>
  </div>
  <div class="card-body">
    <p class="card-text">La Escuela Básica “Campo Elías” es un ente formador y orientador del proceso socializador del Sistema Educativo Bolivariano impartiendo conocimientos hacia el aprendizaje humanístico, significativo</p>
  </div>
</div>

{% endblock content %}

{% block js %}

{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="description" content="Ela Admin - HTML5 Admin Template">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/normalize.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/bootstrap.min.css' %}">
  
  <link rel="stylesheet" href="{% static 'dist_lib/font-awesome-4.7.0/css/font-awesome.min.css' %}">

  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/pe-icon-7-stroke.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/flag-icon.min.css' %}">

  <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/dist_lib/chosen/chosen.min.css' %}">

  
  <title>
    {% block titulo %}
    {% endblock %}
  </title>

  <style type="text/css">
    .header-left{
      margin-top: 15px;
    }
    .right-panel header.header{
      height: 70px;
    }
    .right-panel{
      margin-top: 65px;
    }
    aside.left-panel {
      position: fixed;
      left: 0;
      bottom: 0;
      top: 70px;
    }
    .images{
      height: 55px;
    }
    .logo-escuela{
      height: 100%;
    }
  </style>
  {% block css %}
  {% endblock %}
</head>
<body>
  <!-- Left Panel -->

  <aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">

      <div id="main-menu" class="main-menu collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <a href="{% url 'catalog:home' %}"><i class="menu-icon fa fa-home"></i>Inicio</a>
          </li>
          <li class="menu-title">Biblioteca</li><!-- /.menu-title -->
          <li class="menu-item-has-children dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file-text-o"></i>Gestión de Préstamos</a>
            <ul class="sub-menu children dropdown-menu">
              <li><i class="fa fa-plus"></i><a href="{% url 'loan:crear_prestamo' %}">Préstamo Libros</a></li>
              <li><i class="fa fa-reply"></i><a href="{% url 'loan:devolucion' %}">Devolución Libros</a></li>
              <li><i class="fa fa-plus"></i><a href="{% url 'loan:crear_prestamo_material' %}">Préstamo Material</a></li>
              <li><i class="fa fa-reply"></i><a href="{% url 'loan:devolucion_material' %}">Devolución Material</a></li>
            </ul>
          </li>
          <li class="menu-item-has-children dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-book"></i>Libros</a>
            <ul class="sub-menu children dropdown-menu">
              <li><i class="fa fa-pencil"></i><a href="{% url 'catalog:crear_libro' %}">Registrar Libro</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'catalog:listar_libros' %}">Listado de Libros</a></li>
              <li><i class="fa fa-font"></i><a href="{% url 'catalog:crear_autor' %}">Registrar Autor</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'catalog:listar_autor' %}">Listado de Autores</a></li>
              <li><i class="fa fa-bookmark"></i><a href="{% url 'catalog:crear_editorial' %}">Registrar Editorial</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'catalog:listar_editorial' %}">Lista de Editoriales</a></li>
              <li><i class="fa fa-thumb-tack"></i><a href="{% url 'catalog:crear_autor' %}">Registrar Ubicación</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'catalog:listar_ubicacion' %}">Ubicaciones</a></li>
            </ul>
          </li>
          <li class="menu-item-has-children dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-font"></i>Material</a>
            <ul class="sub-menu children dropdown-menu">
              <li><i class="fa fa-pencil"></i><a href="{% url 'catalog:crear_material' %}">Registrar Material</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'catalog:listar_material' %}">Listado de Material</a></li>
            </ul>
          </li>
          <li class="menu-item-has-children dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Usuarios</a>
            <ul class="sub-menu children dropdown-menu">
              <li><i class="fa fa-pencil"></i><a href="{% url 'account:crear_estudiante' %}">Registrar Estudiante</a></li>
              <li><i class="fa fa-pencil"></i><a href="{% url 'account:crear_personal' %}">Registrar Personal</a></li>
              <li><i class="fa fa-pencil"></i><a href="{% url 'account:crear_visitante' %}">Registrar Visitante</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'account:listar_perfil' %}">Listado de usuarios</a></li>
              <li><i class="fa fa-pencil"></i><a href="{% url 'account:crear_bibliotecario' %}">Registrar Bibliotecario</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'account:listar_bibliotecario' %}">Listado de Bibliotecarios</a></li>
            </ul>
          </li>
          <li class="menu-item-has-children dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Historial de Préstamos</a>
            <ul class="sub-menu children dropdown-menu">
              <li><i class="fa fa-list-ul"></i><a href="{% url 'loan:listar_prestamos' %}">Bibliografico</a></li>
              <li><i class="fa fa-list-ul"></i><a href="{% url 'loan:listar_prestamos_material' %}">No Bibliografico</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  </aside><!-- /#left-panel -->
  <!-- Left Panel -->


  <!-- Right Panel -->
  <div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
      <div class="top-left">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'catalog:home' %}">
            <div class="images">
              <img src="{% static 'images/mpppe.png' %}" alt="Logo-mpppe" class="logo-mpppe">
              <img src="{% static 'images/logo.png' %}" alt="Logo-escuela" class="logo-escuela">
            </div>
          </a>
          <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
      </div>
      <div class="top-right">
        {% if request.user.is_authenticated %}
        <div class="header-menu">
          <div class="header-left">
            <div class="user-area dropdown float-right">
              <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if request.user.perfil_usuario.bibliotecario_perfil.imagen %}
                  <img class="user-avatar rounded-circle" src="{{ request.user.perfil_usuario.bibliotecario_perfil.imagen.url }}" alt="User Avatar">
                {% else %}
                  <img class="user-avatar rounded-circle" src="{% static 'images/perfil.png' %}" alt="User Avatar">
                {% endif %}
              </a>

              <div class="user-menu dropdown-menu">
                <a class="nav-link" href=""><i class="fa fa-cog"></i>Última Conexión</a>
                <a class="nav-link" href="">{{ user.last_login  }}</a>
                <a class="nav-link" href="{% url 'account:logout' %}"><i class="fa fa-power-off"></i>Cerrar sesión</a>
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <div class="header-menu">
          <div class="header-left">
            <a class="btn btn-outline-primary" href="{% url 'account:login' %}">Ingresar</a>
          </div>
        </div>
        {% endif %}

    </header><!-- /header -->
    <!-- Header-->

    <div class="content">
      <div class="animated fadeIn">
        
        
        <div class="row">

          {% block content %}
          {% endblock %}

        </div>
      </div><!-- .animated -->
    </div><!-- .content -->
    <div class="clearfix"></div>

    <footer class="site-footer">
      <div class="footer-inner bg-white">
        <div class="row">
          <div class="offset-sm-6 col-sm-6 text-right">
            Sistema Bibliotecario, 2020
          </div>
        </div>
      </div>
    </footer>


  </div><!-- /#right-panel -->

  <!-- Right Panel -->

  <!-- Scripts -->
  <script src="{% static 'assets/js/dist_lib/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/dist_lib/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/dist_lib/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/dist_lib/jquery.matchHeight.min.js' %}"></script>
  
  <script src="{% static 'assets/js/main.js' %}"></script>
  {% block js %}
  {% endblock %}

</body>
</html>